config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Non autorizado para editar este amigo" if @friend.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder:"Nome" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder:"Apelido" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class: "form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class: "form-control", placeholder:"Teléfono" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter, class: "form-control", placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: "hidden" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html copy.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <td>
    <%= friend.first_name %>
  </td>

  <td>
    <%= friend.last_name %>
  </td>

  <td>
    <%= friend.email %>
  </td>

  <td>
    <%= friend.phone %>
  </td>

  <td>
    <%= friend.twitter %>
  </td>

  <td>
    <%= friend.user_id %>
  </td>
  <td>
    <%= link_to "Mostrar este amigo", friend %>
  </td>

</tr>

app/views/friends/edit.html.erb
<h1>Editando un amigo</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Ver", @friend, class:"btn btn-secondary" %>
  <%= link_to "Voltar", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<h1>Os meus novos amigos falsos</h1>
<br/>
<div id="friends">
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Apelido</th>
        <th scope="col">Email</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Twitter</th>
        <th scope="col">Usuario amigo</th>
        <th scope="col">Mostrar</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <%= render friend %>
        <% end %>
    </tbody>
  </table>


  <!--
    <% @friends.each do |friend| %>
      <%= render friend %>
      <p>
        <%= link_to "Show this friend", friend %>
      </p>
    <% end %>-->
</div>
<br/>
<%= link_to "Novo amigo", new_friend_path, class: "btn btn-primary" %>

app/views/friends/new.html.erb
<h1>Engadir un novo amigo</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Ver todos", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron" id="<%= @friend.first_name %>">
  <h1 class="display-4"><%= @friend.first_name %></h1>
  <p class="lead">Este é oeu amigo <%= @friend.first_name %> <%= @friend.last_name %></p>
  <hr class="my-4">
  <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %>
  
  <div>
    <br/>
    <div>
      <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-primary" %>
    </div>
    <br/>
    <div>
      <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>


  <%= button_to "Back to friends", friends_path, class: "btn btn-secondary"  %>


<div>
  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <%= link_to "Friends App", root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <!--
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      -->

      <li class="nav-item">
        <%= link_to "Lista", friends_path, class: "nav-link"%>
      </li>

      <li class="nav-item">
        <%= link_to "Saúdo", home_about_path, class: "nav-link"%>
      </li>
      
    </ul>
    <ul class="navbar-nav mr-right">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-user"></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                <% if user_signed_in? %>

                    <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item"%>

                    <div class="dropdown-divider"></div>

                   <%= link_to "Sair", destroy_user_session_path, 'data-turbo-method': :delete, class: "dropdown-item" %>

                
                <% else %>

                    <%= link_to "Entrar", new_user_session_path, class: "dropdown-item"%>

                    <%= link_to "Rexistrarse", new_user_registration_path, class: "dropdown-item"%>
                
                <%end%>
            </div>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<br/>

app/views/home/about.html.erb
Olá 🖖! 

app/views/home/index.html.erb
<h1>Friends app</h1>
<p>A minha primeira web com Rails.</p>





<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/35af6a41332353.57a1ce913e889.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/993a9141332353.57a1ce913ee47.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://3.bp.blogspot.com/-rOc9ug9wCUI/VNim6W5EujI/AAAAAAAAAio/NpsV32BebF0/s1600/2.JPG" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://img.izismile.com/img/img2/20090811/ugly_people_39.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-info" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/ef48fae297.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  </head>
  <body>

    <header>
      <%= render "home/header" %>
    </header>

    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>